version: '2'
services:
  wdqs:
    image: ghcr.io/wbstack/queryservice:0.3.6_0.6
    volumes:
      - query-service-data:/wdqs/data
    environment:
      - WIKIBASE_HOST=default.web.mw.localhost:8080
      - WDQS_HOST=wdqs.mw.localhost
      - WDQS_PORT=9999
      - WDQS_ENTITY_NAMESPACES=120,122,146
      - WIKIBASE_SCHEME=http
    restart: unless-stopped
    command: /runBlazegraph.sh
    hostname: wdqs.mw.localhost
    expose:
        - 9999

  elasticsearch-6:
    image: wikibase/elasticsearch:6.8.23-wmde.6
    restart: unless-stopped
    ports:
      - 9200:9200
    networks:
      default:
        aliases:
          - elasticsearch-6.svc
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"

  elasticsearch-7:
    image: wikibase/elasticsearch:7.10.2-wmde.11
    restart: unless-stopped
    ports:
      - 9201:9200
    networks:
      default:
        aliases:
          - elasticsearch-7.svc
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"

volumes:
  query-service-data:
