version: '3.1'

services:

  mediawiki:
    image: ghcr.io/wbstack/mediawiki:1.39-7.4-20230328-0
    volumes:
      - ./maintWikWiki.json:/var/www/html/w/maintWikWiki.json
      - ./new:/var/www/html/w/maintenance/wbaas-api/new
      - ./cleanSql.php:/var/www/html/w/maintenance/wbaas-api/cleanSql.php
    environment:
      WIKWIKI_INFO_FROM: defaults-file
    links:
    - sql-clean
  sql-clean:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: wiki
    networks:
      default:
        aliases:
        - mediawiki-sql
  sql-admin:
    image: adminer:4.6
    ports:
    - 1234:8080
