<?php

// This file is installed automatically when installing laravel/passport with `php artisan passport:install`
// if it doesn't already exist. The autogenerated files don't conform to our code style and so fails linting.
// Keeping correctly styled migrations files in `database/migrations/` resolves this issue.

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    /**
     * Run the migrations.
     */
    public function up(): void {
        Schema::create('oauth_refresh_tokens', function (Blueprint $table) {
            $table->string('id', 100)->primary();
            $table->string('access_token_id', 100)->index();
            $table->boolean('revoked');
            $table->dateTime('expires_at')->nullable();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void {
        Schema::dropIfExists('oauth_refresh_tokens');
    }
};
