<?php

// This file is installed automatically when installing laravel/passport with `php artisan passport:install`
// if it doesn't already exist. The autogenerated files don't conform to our code style and so fails linting.
// Keeping correctly styled migrations files in `database/migrations/` resolves this issue.

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    /**
     * Run the migrations.
     */
    public function up(): void {
        Schema::create('oauth_personal_access_clients', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->unsignedBigInteger('client_id');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void {
        Schema::dropIfExists('oauth_personal_access_clients');
    }
};
